# Generated by Django 5.0.3 on 2024-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='event_images/')),
                ('is_liked', models.BooleanField(default=False)),
                ('user_id', models.IntegerField()),
                ('nol', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(default='none@gmail.com', max_length=200)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
